name = "Unzip"
uuid = "41fe7b60-77ed-43a1-b4f0-825fd5a5650d"
authors = ["Brandon Taylor <brandon.taylor221@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
